improve support for ps2 roms

diff --git a/gladius b/gladius
--- a/gladius
+++ b/gladius
@@ -4,7 +4,7 @@
 MKDIR_P="$(which mkdir) -p"
 RM_F="$(which rm) -f"
 PYTHON="$(which python3)"
-ZIP="$(which 7z)"
+P7ZIP="$(which 7z)"
 
 #Flags
 AUDIO=0
@@ -14,6 +14,7 @@ BUILDDATA=0
 BUILDISO=0
 CLEAN=0
 ECHO=0
+GC=0
 PS=0
 DATAPATH=""
 VERBOSE=""
@@ -31,7 +32,7 @@ AUDIOBEC="audio.bec"
 function unpack_iso()
 {
     if [[ PS -eq 1 ]]; then
-        $ZIP x -o$2 $1
+        $P7ZIP x -o$2 $1
     else
         $PYTHON tools/ngciso-tool.py -unpack $1 $2 $3;
     fi
@@ -66,25 +67,23 @@ function create_bec() { $PYTHON tools/bec-tool.py -pack $1 $2 $3; }
     # $2 - outputFile
 function create_zlib() { $PYTHON tools/zlib-tool.py -c $1 $2; }
 
-function check_ps2
+function check_version
 {
-    if [[ ! -z $ZIP ]]; then
-        $ZIP l $BASEISO > /tmp/test.log
-        if grep -q "PLAYSTATION" /tmp/test.log; then
-            write_verbose "Found PS2 Version."
-            DATABEC="DATA.BEC"
-            AUDIOBEC="AUDIO.BEC"
-            PS=1
-        else
-            write_verbose "Found GC Version."
-        fi
+    if file $BASEISO | grep -qi "udf"; then
+        write_verbose "Found PS2 Version."
+        PS=1
+        DATABEC="DATA.BEC"
+        AUDIOBEC="AUDIO.BEC"
+    elif file $BASEISO | grep -qi "gamecube"; then
+        write_verbose "Found GC Version."
+        GC=1
     else
-        write_verbose "Failed automatic check for PS2 version."
-        echo "Warning: p7zip is required to unpack the PS2 version. Is $BASEISO a PS2 copy?"
-        select yn in "Yes" "No"; do
+        write_verbose "Failed automatic version check"
+        echo "Select your game verison."
+        select yn in "PlayStation2" "GameCube"; do
             case $yn in
-                Yes ) echo "Error: p7zip is not installed. exiting..."; exit 1;;
-                 No ) write_verbose "Manually selected GC Version."; break;;
+                PlayStation2 ) write_verbose "Manually selected PlayStation version."; PS=1; DATABEC="DATA.BEC"; AUDIOBEC="AUDIO.BEC" ;;
+                GameCube ) write_verbose "Manually selected GameCube version."; GC=1;;
             esac
         done
     fi
@@ -131,7 +130,7 @@ EOF
 
 function print_usage
 {
-    echo "Usage: $(basename $0) [--build-audio|-a] [--build-data|-b] [--build-iso|-g] [--clean|-c] [--compress|-z] [--echo|-e] [--help|-h] [--init|-i] [--name|-n] [--rom|-r] [--init-audio|-s] [--verbose|-v]," >&2
+    echo "Usage: $(basename $0) [-gc|-ps] [--build-audio|-a] [--build-data|-b] [--build-iso|-g] [--clean|-c] [--compress|-z] [--echo|-e] [--help|-h] [--init|-i] [--name|-n] [--rom|-r] [--init-audio|-s] [--verbose|-v]," >&2
     echo "    where flags surrounded in '[]' are optional." >&2
 }
 
@@ -152,10 +151,20 @@ for arg in "$@"; do
         "--compress") set -- "$@" "-z"      ;;
              "--dir") set -- "$@" "-d"      ;;
             "--echo") set -- "$@" "-e"      ;;
+              "--gc") if [[ PS -eq 1 ]]; then
+                          echo "$0: Error: --gc amd --ps are mutually exclusive." >&2
+                          exit 1
+                      fi
+                      GC=1 ;;
             "--help") set -- "$@" "-h"      ;;
             "--init") set -- "$@" "-i"      ;;
       "--init-audio") set -- "$@" "-s"      ;;
             "--name") set -- "$@" "-n"      ;;
+              "--ps") if [[ GC -eq 1 ]]; then
+                          echo "$0: Error: --gc and --ps are mutually exclusive." >&2
+                          exit 1
+                      fi
+                      PS=1; DATABEC="DATA.BEC"; AUDIOBEC="AUDIO.BEC" ;;
              "--rom") set -- "$@" "-r"      ;;
          "--verbose") set -- "$@" "-v"      ;;
                   * ) set -- "$@" "$arg"
@@ -184,14 +193,15 @@ done
 if [[ $OPTIND -eq 1 ]]; then print_usage >&2; exit 1; fi
 shift $(($OPTIND - 1))
 
-# Check for PS2 version
-check_ps2 >&2
+if [[ ! GC -eq 1 ]] && [[ ! PS -eq 1 ]]; then
+    # Check for PS2 version
+    write_verbose "Automatically checking game version..."
+    check_version >&2
+fi
 
-if [[ ! -z $DATAPATH ]]; then
-    if [[ PS -eq 1 ]]; then
-        create_zlib ./$BASEDIR/gladius_bec/data/$DATAPATH ./$BASEDIR/gladius_bec/zlib/data/$DATAPATH.zlib
-        exit 0;
-    fi
+if [[ ! -z $DATAPATH ]] && [[ PS -eq 1 ]]; then
+    create_zlib ./$BASEDIR/gladius_bec/data/$DATAPATH ./$BASEDIR/gladius_bec/zlib/data/$DATAPATH.zlib
+    exit 0;
 fi
 
 if [[ ECHO -eq 1 ]]; then
